<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */

namespace App\Http\Livewire\Admin\Logs;

use SIGA\Models\Log;
use SIGA\Table\TableComponent;
use Illuminate\Database\Eloquent\Builder;
use SIGA\Table\Views\Column;

class ListComponent extends TableComponent
{
    public function getCreatedProperty()
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function query(): Builder
    {
        return Log::query();
    }

    public function isDeleted($model = null)
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function isUpdated($model = null)
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function columns(): array
    {
        return [
//            Column::make('Nome', 'name')->searchable(),
//            Column::make('Usuário', 'user')->format(function ($model) {
//                return $model->user->name;
//            }),
            //  Column::make('Model', 'logable_type')->searchable(),
            Column::make('Criado Em', 'created_at')->sortable()->format(function ($model) {
                return date_carbom_format($model->created_at)->format("d/m/Y H:i");
            }),
            Column::make('Descrição', 'description')->view("logs-description")->searchable(),
        ];
    }


    public function layout(): string
    {
        return 'layouts.admin';
    }


    public function route()
    {
        return "admin.segmentos";
    }


    public function view()
    {
        return 'admin.segmentos.list-component';
    }
}
